#!/usr/bin/env python
from __future__ import annotations

import argparse
import subprocess
import zipfile
from pathlib import Path


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--output", required=True)
    args = p.parse_args()
    bundle = Path(args.output)
    bundle.parent.mkdir(parents=True, exist_ok=True)
    root = "Defense4UAVSwarm_q1_real_detector_label_scarcity_bundle"
    fixed_paths = [
        "docs/REAL_DETECTOR_VISDRONE.md",
        "docs/LABEL_SCARCITY_PROTOCOL.md",
        "docs/LIMITATIONS_Q1_UPGRADE.md",
        "docs/REPRODUCE_Q1_UPGRADE.md",
    ]
    result_roots = [
        Path("outputs/results/q1_real_detector"),
        Path("outputs/results/q1_label_scarcity"),
        Path("outputs/results/q1_corruption_robustness"),
        Path("outputs/results/q1_summary"),
        Path("outputs/results/q1_improvement"),
        Path("outputs/results/q1_reproducibility"),
    ]
    with zipfile.ZipFile(bundle, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(
            f"{root}/README_Q1_UPGRADE.md",
            "# Q1 Upgrade\n\n"
            "Real-detector VisDrone validation and label-scarcity protocol.\n\n"
            "Detection JSON files are generated by the reproduce commands and omitted from the compact bundle due to size.\n",
        )
        for path in fixed_paths:
            pth = Path(path)
            if pth.exists():
                zf.write(pth, f"{root}/{path}")
        for result_root in result_roots:
            if not result_root.exists():
                continue
            for pth in sorted(p for p in result_root.rglob("*") if p.is_file()):
                if pth.name.endswith("_visdrone.json") or pth.suffix == ".pkl":
                    continue
                zf.write(pth, f"{root}/{pth.as_posix()}")
        try:
            git = subprocess.check_output(["git", "log", "-1", "--oneline"], text=True).strip()
        except Exception:
            git = "unavailable"
        zf.writestr(f"{root}/reproducibility/git_info.txt", git + "\n")
    print(f"status=ok bundle={bundle}")


if __name__ == "__main__":
    main()
