from __future__ import annotations

import pandas as pd


BASE_COLUMNS = [
    "scenario",
    "model_name",
    "fgsm_loss",
    "eps",
    "frame_id",
    "sequence_id",
    "gt_track_id",
    "pred_track_id",
    "class_id",
    "class_name",
    "x1",
    "y1",
    "x2",
    "y2",
    "confidence",
    "confidence_original",
    "confidence_new",
    "c_i",
    "k_i",
    "k_variant",
    "k_center",
    "k_iou",
    "k_combined",
    "k_gate",
    "k_acc",
    "k_robust_min",
    "d_center",
    "defense_track_id",
    "track_status",
    "assoc_score",
    "assoc_status",
    "missed_frames",
    "gamma_assoc",
    "alpha_base",
    "alpha",
    "alpha_scale",
    "track_age",
    "s_i",
    "x_i",
    "class_top1_conf",
    "class_top2_conf",
    "class_margin",
    "class_entropy",
    "m_i",
    "augmentation_consistency",
    "a_i",
    "temporal_class_stability",
    "t_i",
    "xai_energy_inside",
    "xai_peak_inside",
    "x_i_semantic",
    "semantic_suspicious",
    "semantic_risk_score",
    "Q_raw",
    "Q_i",
    "Q_smooth",
    "beta",
    "soft_conf_floor",
    "reject_patience",
    "low_Q_streak",
    "suspicious",
    "filter_action",
    "tau_existing",
    "tau_new",
    "confirmed_conf_floor",
    "confirm_age",
    "risk_new",
    "suspicious_score",
    "penalty",
    "rank_risk_in_frame",
    "risk_tau",
    "new_conf_tau",
    "penalty_strength",
    "min_penalty",
    "max_reject_per_frame",
    "accepted",
    "t_norm",
    "tau",
    "filter_mode",
    "image_path",
    "latency_ms",
    "xai_triggered",
    "kinematics_enabled",
    "tracking_enabled",
    "mean_abs_perturbation",
    "max_abs_perturbation",
    "mean_gradient_norm",
    "fgsm_loss_clean",
    "fgsm_loss_adv",
    "fgsm_loss_mode_actual",
]


def to_frame(rows: list[dict]) -> pd.DataFrame:
    df = pd.DataFrame(rows)
    for col in BASE_COLUMNS:
        if col not in df.columns:
            df[col] = None
    return df[BASE_COLUMNS]
